name: Build Contract CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"

jobs:
  forge_test:
    strategy:
      fail-fast: true

    name: revolution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Log Solidity version
        run: solc --version

      - name: Log Foundry version
        run: forge --version

      - name: Log Node.js version
        run: node --version

      - name: Update Dependencies
        run: |
          git submodule foreach --recursive 'if [ -f pnpm-lock.yaml ]; then pnpm install; fi'

      - name: Run Forge test
        run: |
          forge test -vvv
        id: test

      - name: Run Geiger Check
        run: |
          forge geiger --check packages/revolution-contracts*
        id: geiger
